[package]
name = "orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
tokio = { version = "1.25", features = ["sync", "rt", "io-std", "io-util", "fs", "process", "macros", "time" ] }
snafu = "0.7.4"
strum = { version = "0.24.1", features = ["derive"] }
tokio-util = { version = "0.7.7", features = ["io", "io-util"] }
tokio-stream = "0.1.12"

[dev-dependencies]
tempdir = "0.3.7"
